# User microservice - conecta a PostgreSQL local
services:
  user-service:
    build:
      context: ../../..
      dockerfile: src/microservices/user/Dockerfile
    ports:
      - "3001:3001"
    environment:
      USER_NODE_ENV: production
      USER_SERVICE_PORT: 3001
      USER_DB_HOST: host.docker.internal
      USER_DB_PORT: 5432
      USER_DB_USERNAME: postgres
      USER_DB_PASSWORD: postgres123
      USER_DB_NAME: odoonto
      USER_RMQ_URL: amqp://admin:admin@rabbitmq:5672
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: user-rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
