# User microservice - standalone
version: "3.9"

services:
  user-svc:
    build: .
    container_name: user-microservice-standalone
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    env_file: .env
    networks:
      - user-network
    restart: unless-stopped

networks:
  user-network:
    driver: bridge
