# User microservice - usando archivo .env
services:
  user-service:
    build:
      context: ../../..
      dockerfile: src/microservices/user/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped 