version: "3.8"

services:
  user-service:
    build:
      context: ../../..
      dockerfile: src/microservices/user/Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      USER_SERVICE_PORT: 3001
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_NAME: odoonto
    secrets:
      - db_password
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

secrets:
  db_password:
    file: ./secrets/db_password.txt
