# Infraestructura compartida - solo para desarrollo local
version: '3.9'

services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - microservices

  postgres:
    container_name: postgres-container
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: odoonto
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservices

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  pgdata:
