# Wallet microservice - standalone
version: '3.9'

services:
  wallet-svc:
    build: .
    container_name: wallet-microservice-standalone
    ports:
      - 3002:3000
    environment:
      - NODE_ENV=production
      - RMQ_URL=${RMQ_URL:-amqp://localhost:5672}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_DATABASE=${DB_DATABASE:-odoonto}
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge
